2024-03-05 23:49:50,956 - Error getting GPU usage: No data
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:50:01,007 - Error getting GPU usage: Unknown Error
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:50:11,103 - Error getting GPU usage: Unknown Error
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:50:21,123 - Error getting GPU usage: Unknown Error
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:50:31,890 - Error getting GPU usage: Unknown Error
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:50:45,108 - Error getting GPU usage: Unknown Error
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:50:55,128 - Error getting GPU usage: Unknown Error
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:51:14,592 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:51:25,465 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:51:37,919 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:51:58,511 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:52:15,341 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:52:33,217 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:52:43,936 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:52:54,044 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:53:03,041 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:53:13,068 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:53:23,095 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:53:33,124 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:53:46,176 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:53:56,217 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:54:06,266 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:54:08,225 - Something went wrong with pytorch lightning. one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [128, 10]], which is output 0 of AsStridedBackward0, is at version 783; expected version 782 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
[in /fedstellar/fedstellar/../fedstellar/learning/pytorch/lightninglearner.py:155]
2024-03-05 23:54:08,231 - Traceback (most recent call last):
  File "/fedstellar/fedstellar/../fedstellar/learning/pytorch/lightninglearner.py", line 152, in fit
    self.__trainer.fit(self.model, self.data)
  File "/usr/local/lib/python3.11/dist-packages/lightning/pytorch/trainer/trainer.py", line 544, in fit
    call._call_and_handle_interrupt(
  File "/usr/local/lib/python3.11/dist-packages/lightning/pytorch/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/lightning/pytorch/trainer/trainer.py", line 580, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/usr/local/lib/python3.11/dist-packages/lightning/pytorch/trainer/trainer.py", line 989, in _run
    results = self._run_stage()
              ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/lightning/pytorch/trainer/trainer.py", line 1035, in _run_stage
    self.fit_loop.run()
  File "/usr/local/lib/python3.11/dist-packages/lightning/pytorch/loops/fit_loop.py", line 202, in run
    self.advance()
  File "/usr/local/lib/python3.11/dist-packages/lightning/pytorch/loops/fit_loop.py", line 359, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "/usr/local/lib/python3.11/dist-packages/lightning/pytorch/loops/training_epoch_loop.py", line 136, in run
    self.advance(data_fetcher)
  File "/usr/local/lib/python3.11/dist-packages/lightning/pytorch/loops/training_epoch_loop.py", line 240, in advance
    batch_output = self.automatic_optimization.run(trainer.optimizers[0], batch_idx, kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/lightning/pytorch/loops/optimization/automatic.py", line 187, in run
    self._optimizer_step(batch_idx, closure)
  File "/usr/local/lib/python3.11/dist-packages/lightning/pytorch/loops/optimization/automatic.py", line 265, in _optimizer_step
    call._call_lightning_module_hook(
  File "/usr/local/lib/python3.11/dist-packages/lightning/pytorch/trainer/call.py", line 157, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/lightning/pytorch/core/module.py", line 1291, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/usr/local/lib/python3.11/dist-packages/lightning/pytorch/core/optimizer.py", line 151, in step
    step_output = self._strategy.optimizer_step(self._optimizer, closure, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/lightning/pytorch/strategies/strategy.py", line 230, in optimizer_step
    return self.precision_plugin.optimizer_step(optimizer, model=model, closure=closure, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/lightning/pytorch/plugins/precision/precision.py", line 117, in optimizer_step
    return optimizer.step(closure=closure, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/optim/optimizer.py", line 373, in wrapper
    out = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/optim/optimizer.py", line 76, in _use_grad
    ret = func(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/optim/adam.py", line 143, in step
    loss = closure()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/lightning/pytorch/plugins/precision/precision.py", line 104, in _wrap_closure
    closure_result = closure()
                     ^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/lightning/pytorch/loops/optimization/automatic.py", line 140, in __call__
    self._result = self.closure(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/lightning/pytorch/loops/optimization/automatic.py", line 135, in closure
    self._backward_fn(step_output.closure_loss)
  File "/usr/local/lib/python3.11/dist-packages/lightning/pytorch/loops/optimization/automatic.py", line 236, in backward_fn
    call._call_strategy_hook(self.trainer, "backward", loss, optimizer)
  File "/usr/local/lib/python3.11/dist-packages/lightning/pytorch/trainer/call.py", line 309, in _call_strategy_hook
    output = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/lightning/pytorch/strategies/strategy.py", line 204, in backward
    self.precision_plugin.backward(closure_loss, self.lightning_module, optimizer, *args, **kwargs)
  File "/usr/local/lib/python3.11/dist-packages/lightning/pytorch/plugins/precision/precision.py", line 69, in backward
    model.backward(tensor, *args, **kwargs)
  File "/usr/local/lib/python3.11/dist-packages/lightning/pytorch/core/module.py", line 1078, in backward
    loss.backward(*args, **kwargs)
  File "/usr/local/lib/python3.11/dist-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/usr/local/lib/python3.11/dist-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [128, 10]], which is output 0 of AsStridedBackward0, is at version 783; expected version 782 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

[in /fedstellar/fedstellar/../fedstellar/learning/pytorch/lightninglearner.py:157]
2024-03-05 23:54:16,315 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:54:26,352 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:54:37,755 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:54:47,787 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:54:57,832 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:55:07,883 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:55:17,929 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:55:27,980 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:55:39,004 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:55:49,072 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:55:59,112 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:56:09,151 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:56:19,203 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:56:29,256 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:56:39,297 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:56:49,348 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:56:59,387 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:57:09,419 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:57:19,461 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:57:29,503 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:57:39,542 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:57:45,616 - (192.168.50.5:45000) Models ready in a late round. Ignored. 0 != 2 / 1
[in /fedstellar/fedstellar/../fedstellar/node.py:427]
2024-03-05 23:57:46,835 - (192.168.50.5:45000) Models ready in a late round. Ignored. 0 != 2 / 1
[in /fedstellar/fedstellar/../fedstellar/node.py:427]
2024-03-05 23:57:48,410 - (192.168.50.5:45000) Models ready in a late round. Ignored. 0 != 2 / 1
[in /fedstellar/fedstellar/../fedstellar/node.py:427]
2024-03-05 23:57:49,584 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:57:59,621 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:58:09,667 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:58:19,713 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:58:29,742 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:58:39,781 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:58:49,822 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:59:03,705 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:59:13,754 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:59:23,781 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:59:33,816 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:59:43,296 - (192.168.50.5:45000) Models ready in a late round. Ignored. 0 != 3 / 2
[in /fedstellar/fedstellar/../fedstellar/node.py:427]
2024-03-05 23:59:43,845 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:59:44,165 - (192.168.50.5:45000) Models ready in a late round. Ignored. 0 != 3 / 2
[in /fedstellar/fedstellar/../fedstellar/node.py:427]
2024-03-05 23:59:44,214 - (192.168.50.5:45000) Models ready in a late round. Ignored. 0 != 3 / 2
[in /fedstellar/fedstellar/../fedstellar/node.py:427]
2024-03-05 23:59:53,888 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-06 00:00:03,938 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-06 00:00:14,013 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-06 00:00:24,052 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-06 00:00:34,085 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-06 00:00:44,125 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-06 00:00:54,168 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-06 00:01:04,202 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-06 00:01:14,242 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-06 00:01:24,284 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-06 00:01:33,941 - (192.168.50.5:45000) Models ready in a late round. Ignored. 0 != 4 / 3
[in /fedstellar/fedstellar/../fedstellar/node.py:427]
2024-03-06 00:01:34,073 - (192.168.50.5:45000) Models ready in a late round. Ignored. 0 != 4 / 3
[in /fedstellar/fedstellar/../fedstellar/node.py:427]
2024-03-06 00:01:34,317 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-06 00:01:35,166 - (192.168.50.5:45000) Models ready in a late round. Ignored. 0 != 4 / 3
[in /fedstellar/fedstellar/../fedstellar/node.py:427]
2024-03-06 00:01:44,344 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-06 00:01:54,389 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-06 00:02:04,424 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-06 00:02:14,465 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-06 00:02:24,519 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-06 00:02:34,548 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-06 00:02:44,595 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-06 00:02:54,635 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-06 00:03:04,668 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-06 00:03:14,708 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-06 00:03:24,747 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-06 00:03:34,895 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-06 00:03:44,926 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-06 00:03:57,243 - (192.168.50.5:45000) send_message (gRPC) | Cannot send message beat to 192.168.50.3:45000. Error: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Deadline Exceeded", grpc_status:4, created_time:"2024-03-06T00:03:51.678666493+01:00"}"
>
[in /fedstellar/fedstellar/../fedstellar/neighbors.py:131]
2024-03-06 00:03:57,326 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-06 00:04:07,347 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-06 00:04:17,366 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-06 00:04:27,393 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-06 00:04:41,507 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-06 00:04:51,375 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-06 00:05:01,635 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-06 00:05:11,658 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-06 00:05:21,858 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-06 00:05:31,880 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-06 00:05:42,665 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-06 00:05:52,691 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-06 00:06:02,720 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-06 00:06:12,746 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-06 00:06:22,779 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-06 00:06:32,815 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-06 00:06:42,849 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-06 00:06:52,882 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-06 00:07:02,915 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-06 00:07:12,936 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-06 00:07:22,981 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-06 00:07:33,006 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-06 00:07:43,033 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-06 00:07:53,064 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-06 00:08:03,097 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-06 00:08:13,125 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-06 00:08:23,163 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-06 00:08:33,193 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-06 00:08:43,214 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-06 00:08:53,249 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-06 00:09:03,277 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-06 00:09:13,316 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-06 00:09:23,352 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-06 00:09:33,373 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-06 00:09:43,396 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
