2024-03-05 23:32:27,721 - Error getting GPU usage: No data
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:32:37,752 - Error getting GPU usage: Unknown Error
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:32:47,767 - Error getting GPU usage: Unknown Error
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:32:57,821 - Error getting GPU usage: Unknown Error
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:33:07,847 - Error getting GPU usage: Unknown Error
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:33:17,862 - Error getting GPU usage: Unknown Error
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:33:27,899 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:33:39,727 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:33:49,765 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:34:00,142 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:34:10,195 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:34:20,231 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:34:30,296 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:34:39,802 - Something went wrong with pytorch lightning. one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [128, 10]], which is output 0 of AsStridedBackward0, is at version 1287; expected version 1286 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
[in /fedstellar/fedstellar/../fedstellar/learning/pytorch/lightninglearner.py:155]
2024-03-05 23:34:39,807 - Traceback (most recent call last):
  File "/fedstellar/fedstellar/../fedstellar/learning/pytorch/lightninglearner.py", line 152, in fit
    self.__trainer.fit(self.model, self.data)
  File "/usr/local/lib/python3.11/dist-packages/lightning/pytorch/trainer/trainer.py", line 544, in fit
    call._call_and_handle_interrupt(
  File "/usr/local/lib/python3.11/dist-packages/lightning/pytorch/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/lightning/pytorch/trainer/trainer.py", line 580, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/usr/local/lib/python3.11/dist-packages/lightning/pytorch/trainer/trainer.py", line 989, in _run
    results = self._run_stage()
              ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/lightning/pytorch/trainer/trainer.py", line 1035, in _run_stage
    self.fit_loop.run()
  File "/usr/local/lib/python3.11/dist-packages/lightning/pytorch/loops/fit_loop.py", line 202, in run
    self.advance()
  File "/usr/local/lib/python3.11/dist-packages/lightning/pytorch/loops/fit_loop.py", line 359, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "/usr/local/lib/python3.11/dist-packages/lightning/pytorch/loops/training_epoch_loop.py", line 136, in run
    self.advance(data_fetcher)
  File "/usr/local/lib/python3.11/dist-packages/lightning/pytorch/loops/training_epoch_loop.py", line 240, in advance
    batch_output = self.automatic_optimization.run(trainer.optimizers[0], batch_idx, kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/lightning/pytorch/loops/optimization/automatic.py", line 187, in run
    self._optimizer_step(batch_idx, closure)
  File "/usr/local/lib/python3.11/dist-packages/lightning/pytorch/loops/optimization/automatic.py", line 265, in _optimizer_step
    call._call_lightning_module_hook(
  File "/usr/local/lib/python3.11/dist-packages/lightning/pytorch/trainer/call.py", line 157, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/lightning/pytorch/core/module.py", line 1291, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/usr/local/lib/python3.11/dist-packages/lightning/pytorch/core/optimizer.py", line 151, in step
    step_output = self._strategy.optimizer_step(self._optimizer, closure, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/lightning/pytorch/strategies/strategy.py", line 230, in optimizer_step
    return self.precision_plugin.optimizer_step(optimizer, model=model, closure=closure, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/lightning/pytorch/plugins/precision/precision.py", line 117, in optimizer_step
    return optimizer.step(closure=closure, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/optim/optimizer.py", line 373, in wrapper
    out = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/optim/optimizer.py", line 76, in _use_grad
    ret = func(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/optim/adam.py", line 143, in step
    loss = closure()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/lightning/pytorch/plugins/precision/precision.py", line 104, in _wrap_closure
    closure_result = closure()
                     ^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/lightning/pytorch/loops/optimization/automatic.py", line 140, in __call__
    self._result = self.closure(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/lightning/pytorch/loops/optimization/automatic.py", line 135, in closure
    self._backward_fn(step_output.closure_loss)
  File "/usr/local/lib/python3.11/dist-packages/lightning/pytorch/loops/optimization/automatic.py", line 236, in backward_fn
    call._call_strategy_hook(self.trainer, "backward", loss, optimizer)
  File "/usr/local/lib/python3.11/dist-packages/lightning/pytorch/trainer/call.py", line 309, in _call_strategy_hook
    output = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/lightning/pytorch/strategies/strategy.py", line 204, in backward
    self.precision_plugin.backward(closure_loss, self.lightning_module, optimizer, *args, **kwargs)
  File "/usr/local/lib/python3.11/dist-packages/lightning/pytorch/plugins/precision/precision.py", line 69, in backward
    model.backward(tensor, *args, **kwargs)
  File "/usr/local/lib/python3.11/dist-packages/lightning/pytorch/core/module.py", line 1078, in backward
    loss.backward(*args, **kwargs)
  File "/usr/local/lib/python3.11/dist-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/usr/local/lib/python3.11/dist-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [128, 10]], which is output 0 of AsStridedBackward0, is at version 1287; expected version 1286 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

[in /fedstellar/fedstellar/../fedstellar/learning/pytorch/lightninglearner.py:157]
2024-03-05 23:34:40,326 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:34:50,353 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:35:00,387 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:35:10,459 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:35:20,494 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:35:30,530 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:35:40,554 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:35:50,616 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:36:00,661 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:36:10,698 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:36:20,735 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:36:27,681 - (192.168.50.4:45000) Models ready in a late round. Ignored. 0 != 2 / 1
[in /fedstellar/fedstellar/../fedstellar/node.py:427]
2024-03-05 23:36:29,292 - (192.168.50.4:45000) Models ready in a late round. Ignored. 0 != 2 / 1
[in /fedstellar/fedstellar/../fedstellar/node.py:427]
2024-03-05 23:36:30,791 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:36:40,815 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:36:50,847 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:37:00,875 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:37:10,939 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:37:20,968 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:37:21,642 - (192.168.50.4:45000) Models ready in a late round. Ignored. 0 != 3 / 2
[in /fedstellar/fedstellar/../fedstellar/node.py:427]
2024-03-05 23:37:22,566 - (192.168.50.4:45000) Models ready in a late round. Ignored. 0 != 3 / 2
[in /fedstellar/fedstellar/../fedstellar/node.py:427]
2024-03-05 23:37:30,999 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:37:41,099 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:37:51,133 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:38:01,159 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:38:11,186 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:38:18,189 - (192.168.50.4:45000) Models ready in a late round. Ignored. 0 != 4 / 3
[in /fedstellar/fedstellar/../fedstellar/node.py:427]
2024-03-05 23:38:18,544 - (192.168.50.4:45000) Models ready in a late round. Ignored. 0 != 4 / 3
[in /fedstellar/fedstellar/../fedstellar/node.py:427]
2024-03-05 23:38:21,216 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:38:31,278 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:38:41,304 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:38:51,336 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:39:01,372 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:39:11,428 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:39:12,558 - (192.168.50.4:45000) Models ready in a late round. Ignored. 0 != 5 / 4
[in /fedstellar/fedstellar/../fedstellar/node.py:427]
2024-03-05 23:39:12,613 - (192.168.50.4:45000) Models ready in a late round. Ignored. 0 != 5 / 4
[in /fedstellar/fedstellar/../fedstellar/node.py:427]
2024-03-05 23:39:21,452 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:39:31,488 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:39:41,522 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:39:51,587 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:40:01,623 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:40:06,246 - (192.168.50.4:45000) Models ready in a late round. Ignored. 0 != 6 / 5
[in /fedstellar/fedstellar/../fedstellar/node.py:427]
2024-03-05 23:40:06,509 - (192.168.50.4:45000) Models ready in a late round. Ignored. 0 != 6 / 5
[in /fedstellar/fedstellar/../fedstellar/node.py:427]
2024-03-05 23:40:11,646 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:40:21,669 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:40:31,729 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:40:41,752 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:40:51,784 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:40:57,374 - (192.168.50.4:45000) Models ready in a late round. Ignored. 0 != 7 / 6
[in /fedstellar/fedstellar/../fedstellar/node.py:427]
2024-03-05 23:41:00,285 - (192.168.50.4:45000) Models ready in a late round. Ignored. 0 != 7 / 6
[in /fedstellar/fedstellar/../fedstellar/node.py:427]
2024-03-05 23:41:01,818 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:41:11,876 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:41:21,912 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:41:31,946 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:41:41,977 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:41:51,423 - (192.168.50.4:45000) Models ready in a late round. Ignored. 0 != 8 / 7
[in /fedstellar/fedstellar/../fedstellar/node.py:427]
2024-03-05 23:41:52,029 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:41:52,462 - (192.168.50.4:45000) Models ready in a late round. Ignored. 0 != 8 / 7
[in /fedstellar/fedstellar/../fedstellar/node.py:427]
2024-03-05 23:42:02,050 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:42:12,088 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:42:22,128 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:42:32,177 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:42:42,212 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:42:46,774 - (192.168.50.4:45000) Models ready in a late round. Ignored. 0 != 9 / 8
[in /fedstellar/fedstellar/../fedstellar/node.py:427]
2024-03-05 23:42:47,982 - (192.168.50.4:45000) Models ready in a late round. Ignored. 0 != 9 / 8
[in /fedstellar/fedstellar/../fedstellar/node.py:427]
2024-03-05 23:42:52,244 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:43:02,287 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:43:12,350 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:43:22,381 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:43:32,414 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:43:42,444 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:43:52,513 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:44:02,549 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:44:12,586 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:44:22,617 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:44:32,648 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:44:42,679 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:44:52,705 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:45:02,740 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:45:12,777 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:45:22,807 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:45:32,830 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:45:42,861 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:45:52,894 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:46:02,924 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:46:12,947 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:46:22,981 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:46:33,010 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:46:43,032 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:46:53,064 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:47:03,095 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:47:13,124 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:47:23,145 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:47:33,178 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:47:43,211 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
2024-03-05 23:47:53,242 - Error getting GPU usage: Not Supported
[in /fedstellar/fedstellar/../fedstellar/node.py:726]
